require 'common'
require 'cext/noyes_c'
require 'ts_fast'

make_test 'NoyesC', 'Preemphasis'
make_test 'NoyesC', 'Segment'
make_test 'NoyesC', 'HammingWindow'
make_test 'NoyesC', 'PowerSpec'
make_test 'NoyesC', 'MelFilter'
make_test 'NoyesC', 'LogCompress'
make_test 'NoyesC', 'DCT'
make_test 'NoyesC', 'LiveCMN'
make_test 'NoyesC', 'EndOfUtterance'
make_test 'NoyesC', 'PowerSpec'
make_test 'NoyesC', 'DiscreteFourierTransform'
#make_test 'NoyesC', 'Queue'
