require 'noyes'
require 'ts_fast'

make_test 'Noyes', 'Delta'
make_test 'Noyes', 'DCT'
make_test 'Noyes', 'DiscreteFourierTransform'
make_test 'Noyes', 'DSL'
make_test 'Noyes', 'HammingWindow'
make_test 'Noyes', 'LogCompress'
make_test 'Noyes', 'MelFilter'
make_test 'Noyes', 'PowerSpec'
make_test 'Noyes', 'Preemphasis'
make_test 'Noyes', 'Segment'
