require 'noyes_java'
require 'ts_fast'

make_test 'NoyesJava', 'Delta'
make_test 'NoyesJava', 'DCT'
make_test 'NoyesJava', 'DiscreteFourierTransform'
make_test 'NoyesJava', 'DSL'
make_test 'NoyesJava', 'HammingWindow'
make_test 'NoyesJava', 'LogCompress'
make_test 'NoyesJava', 'MelFilter'
make_test 'NoyesJava', 'PowerSpec'
make_test 'NoyesJava', 'Preemphasis'
make_test 'NoyesJava', 'Segment'
